services:
    dev:
        container_name: ttk-global
        image: ttk-global:1.0.0
        build:
            context: .
        restart: always
        ports:
            - 3000:3000
        networks:
            - ttk
networks:
    ttk: 
        driver: bridge